Flatten the Tritium proxy to avoid excessive stack frames
Note that this pushes the invoke method above the 35 byte inline
threshold to 102 bytes, which is still below the 325 byte hot
method threshiold.

Before:
```
java.lang.RuntimeException: Stack Trace
        at com.palantir.DemoMain.run(DemoMain.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.palantir.tritium.proxy.InvocationEventProxy.execute(InvocationEventProxy.java:149)
        at com.palantir.tritium.proxy.InvocationEventProxy.invoke(InvocationEventProxy.java:140)
        at com.palantir.tritium.proxy.InvocationEventProxy.instrumentInvocation(InvocationEventProxy.java:120)
        at com.palantir.tritium.proxy.InvocationEventProxy.handleInvocation(InvocationEventProxy.java:99)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
        at com.sun.proxy.$Proxy0.run(Unknown Source)
        at com.palantir.DemoMain.main(DemoMain.java:27)
```

After:
```
java.lang.RuntimeException: Stack Trace
        at com.palantir.DemoMain.run(DemoMain.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.palantir.tritium.proxy.InvocationEventProxy.invoke(InvocationEventProxy.java:102)
        at com.sun.proxy.$Proxy0.run(Unknown Source)
        at com.palantir.DemoMain.main(DemoMain.java:27)
```